### ISSUE TITLE
Why azdev only allow run in virtualenv?

### ISSUE THREAD

**Issue by haroldrandom** [Azure/azure-cli-dev-tools#150]
If not install azdev in a virtualenv, it will throw errors:
```
root@098c3f2011fb:/# azdev setup -c -r azure-cli-extensions/
Traceback (most recent call last):
  File "/usr/local/bin/azdev", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/azdev/__main__.py", line 40, in main
    config_dir=get_azdev_config_dir())
  File "/usr/local/lib/python3.6/dist-packages/azdev/utilities/config.py", line 24, in get_azdev_config_dir
    _, env_name = os.path.splitdrive(get_env_path())
  File "/usr/lib/python3.6/posixpath.py", line 138, in splitdrive
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by Mossaka** [comment]
Any answer to this? I also encountered this error after installing `azdev` without using a virtual env.

**Comment by dtometzki** [comment]
Hello,

Any answer to this? 

Best regards
Damian
