### ISSUE TITLE
azdev linter --include-whl-extensions vmware

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-cli-dev-tools#167]
Any idea why linter is failing here?

azdev linter fails with this error from https://github.com/Azure/azure-cli-extensions/pull/1367 :
```
azdev linter --include-whl-extensions vmware
Traceback (most recent call last):
  File "scripts/ci/verify_linter.py", line 213, in <module>
    main()
  File "scripts/ci/verify_linter.py", line 195, in main
    linter_on_external_extension(modified_files[0])
  File "scripts/ci/verify_linter.py", line 160, in linter_on_external_extension
    azdev_extension.linter()
  File "scripts/ci/verify_linter.py", line 77, in linter
    self._cmd('azdev linter --include-whl-extensions {}'.format(self.extension_name))
  File "scripts/ci/verify_linter.py", line 68, in _cmd
    check_call(cmd, shell=True)
  File "/opt/hostedtoolcache/Python/3.6.10/x64/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'azdev linter --include-whl-extensions vmware' returned non-zero exit status 1.
```

The extension installs and works just fine with:
```
az extension add -s https://github.com/virtustream/azure-vmware-virtustream-cli-extension/releases/download/0.5.3/vmware-0.5.3-py2.py3-none-any.whl -y
```

**Comment by ctaggart** [comment]
Looks like it was a bug in extensions CI, fixed by https://github.com/Azure/azure-cli-extensions/pull/1392
