### ISSUE TITLE
No module named 'knack.experimental' error after upgrading azdev 

### ISSUE THREAD

**Issue by audunn** [Azure/azure-cli-dev-tools#198]
On Windows after attempting to upgrade azdev to get my environment up to the latest. I get an error running azdev commands throws `No module named 'knack.experimental' `

```
❯ azdev style netappfiles

===============
| Style Check |
===============

No module named 'knack.experimental'
Traceback (most recent call last):
  File "c:\users\audunn\source\repos\audunn\azure-cli\env\lib\site-packages\knack\cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "c:\users\audunn\source\repos\audunn\azure-cli\env\lib\site-packages\knack\invocation.py", line 208, in execute
    cmd_result = parsed_args.func(params)
  File "c:\users\audunn\source\repos\audunn\azure-cli\env\lib\site-packages\knack\commands.py", line 139, in __call__
    return self.handler(*args, **kwargs)
  File "c:\users\audunn\source\repos\audunn\azure-cli\env\lib\site-packages\knack\commands.py", line 246, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "c:\users\audunn\source\repos\audunn\azure-cli\env\lib\site-packages\azdev\operations\style.py", line 34, in check_style
    selected_modules = get_path_table(include_only=modules)
  File "c:\users\audunn\source\repos\audunn\azure-cli\env\lib\site-packages\azdev\utilities\path.py", line 193, in get_path_table
    from azure.cli.core.extension import EXTENSIONS_DIR  # pylint: disable=import-error
  File "c:\users\audunn\source\repos\audunn\azure-cli\src\azure-cli-core\azure\cli\core\__init__.py", line 23, in <module>
    from knack.experimental import ExperimentalItem
ModuleNotFoundError: No module named 'knack.experimental'
```

**Comment by audunn** [comment]
Anyone?

**Comment by haroldrandom** [comment]
Close as resolved other place.
