### ISSUE TITLE
`azdev test` gets error with master branch

### ISSUE THREAD

**Issue by Juliehzl** [Azure/azure-cli-dev-tools#275]
```
❯ azdev test test_storage_blob_upload --discover

=============
| Run Tests |
=============


=====================
| Discovering Tests |
=====================

(six 1.14.0 (e:\microsoft\azurecli\azure-cli-extensions\env\lib\site-packages), Requirement.parse('six==1.12'), {'astroid'})
Traceback (most recent call last):
  File "e:\microsoft\azurecli\azure-cli-extensions\env\lib\site-packages\pkg_resources\__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "e:\microsoft\azurecli\azure-cli-extensions\env\lib\site-packages\pkg_resources\__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "e:\microsoft\azurecli\azure-cli-extensions\env\lib\site-packages\pkg_resources\__init__.py", line 782, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (six 1.14.0 (e:\microsoft\azurecli\azure-cli-extensions\env\lib\site-packages), Requirement.parse('six==1.12'), {'astroid'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\microsoft\azurecli\azure-cli-extensions\env\lib\site-packages\knack\cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "e:\microsoft\azurecli\azure-cli-extensions\env\lib\site-packages\knack\invocation.py", line 225, in execute
    cmd_result = parsed_args.func(params)
  File "e:\microsoft\azurecli\azure-cli-extensions\env\lib\site-packages\knack\commands.py", line 148, in __call__
    return self.handler(*args, **kwargs)
  File "e:\microsoft\azurecli\azure-cli-extensions\env\lib\site-packages\knack\commands.py", line 255, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "e:\microsoft\azurecli\azure-cli-dev-tools\azdev\operations\testtool\__init__.py", line 48, in run_tests
    test_index = _get_test_index(profile or current_profile(), discover)
  File "e:\microsoft\azurecli\azure-cli-dev-tools\azdev\operations\testtool\__init__.py", line 320, in _get_test_index
    test_index = _discover_tests(profile)
  File "e:\microsoft\azurecli\azure-cli-dev-tools\azdev\operations\testtool\__init__.py", line 240, in _discover_tests
    tests = _discover_module_tests(mod_name, mod_data)
  File "e:\microsoft\azurecli\azure-cli-dev-tools\azdev\operations\testtool\__init__.py", line 174, in _discover_module_tests
    module = import_module(test_file_path)
  File "C:\Users\zuh\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "e:\microsoft\azurecli\azure-cli\src\azure-cli\azure\cli\command_modules\appservice\tests\latest\test_devops_build_commands_thru_mock.py", line 10, in <module>
    from azure.cli.command_modules.appservice.azure_devops_build_interactive import (
  File "e:\microsoft\azurecli\azure-cli\src\azure-cli\azure\cli\command_modules\appservice\azure_devops_build_interactive.py", line 31, in <module>
    from .azure_devops_build_provider import AzureDevopsBuildProvider
  File "e:\microsoft\azurecli\azure-cli\src\azure-cli\azure\cli\command_modules\appservice\azure_devops_build_provider.py", line 7, in <module>
    from azure_functions_devops_build.project.project_manager import ProjectManager
  File "e:\microsoft\azurecli\azure-cli-extensions\env\lib\site-packages\azure_functions_devops_build\project\project_manager.py", line 11, in <module>
    from vsts.exceptions import VstsServiceError
  File "e:\microsoft\azurecli\azure-cli-extensions\env\lib\site-packages\vsts\__init__.py", line 5, in <module>
    import pkg_resources
  File "e:\microsoft\azurecli\azure-cli-extensions\env\lib\site-packages\pkg_resources\__init__.py", line 3098, in <module>
    @_call_aside
  File "e:\microsoft\azurecli\azure-cli-extensions\env\lib\site-packages\pkg_resources\__init__.py", line 3082, in _call_aside
    f(*args, **kwargs)
  File "e:\microsoft\azurecli\azure-cli-extensions\env\lib\site-packages\pkg_resources\__init__.py", line 3111, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "e:\microsoft\azurecli\azure-cli-extensions\env\lib\site-packages\pkg_resources\__init__.py", line 575, in _build_master
    return cls._build_from_requirements(__requires__)
  File "e:\microsoft\azurecli\azure-cli-extensions\env\lib\site-packages\pkg_resources\__init__.py", line 588, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "e:\microsoft\azurecli\azure-cli-extensions\env\lib\site-packages\pkg_resources\__init__.py", line 782, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (six 1.14.0 (e:\microsoft\azurecli\azure-cli-extensions\env\lib\site-packages), Requirement.parse('six==1.12'), {'astroid'})
```

![image](https://user-images.githubusercontent.com/49508232/102195139-2563ac00-3ef9-11eb-8967-58cde8d5cac9.png)

**Comment by bquantump** [comment]
Can't reproduce this.

First I don't see a test for just storage_blob_upload

There are many with that prefix though like: storage_blob_upload_2G_file, storage_blob_upload_64mb_file

All storage test pass:

----------------------------------------- generated xml file: /mnt/c/Users/stevens/projects/clitest/azure-cli-dev-tools/clitest/.azdev/env_config/mnt/c/Users/stevens/projects/clitest/azure-cli-dev-tools/clitest/test_results.xml ------------------------------------------
================================================================================================================ 130 passed, 36 skipped in 433.40s (0:07:13) =================**

**

**Comment by YalinLi0312** [comment]
Same, can't reproduce in my end in Windows.

@Juliehzl I don't see the RP test_storage_blob_upload, so tried with `azdev test storage --discover`, all tests are passed. Can you provide the exact RP you are testing? Are you testing inside a virtual environment which set up with the latest azdev?
