### ISSUE TITLE
Cannot install extensions

### ISSUE THREAD

**Issue by gsscoder** [Azure/azure-cli-dev-tools#277]
Hi there :)
I've followed video tutorial instructions in Windows machine. I'm unable to install extensions.
My python3 version is **3.9.1.**
Here is the command:
```powershell
$ azdev extension add azure-firewall
```
Here is the result:
```powershell
Command '['C:\\Users\\coder\\source\\repos\\env\\Scripts\\python', '-m', 'pip', 'install', '-e', 'C:\\Users\\coder\\source\\repos\\azure-cli-extensions\\src\\azure-firewall']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "c:\users\coder\source\repos\env\lib\site-packages\knack\cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "c:\users\coder\source\repos\env\lib\site-packages\knack\invocation.py", line 208, in execute
    cmd_result = parsed_args.func(params)
  File "c:\users\coder\source\repos\env\lib\site-packages\knack\commands.py", line 139, in __call__
    return self.handler(*args, **kwargs)
  File "c:\users\coder\source\repos\env\lib\site-packages\knack\commands.py", line 246, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "c:\users\coder\source\repos\env\lib\site-packages\azdev\operations\extensions\__init__.py", line 43, in add_extension
    raise result.error  # pylint: disable=raising-bad-type
  File "c:\users\coder\source\repos\env\lib\site-packages\azdev\utilities\command.py", line 50, in cmd
    output = subprocess.check_output(
  File "C:\Python39\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Python39\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\coder\\source\\repos\\env\\Scripts\\python', '-m', 'pip', 'install', '-e', 'C:\\Users\\coder\\source\\repos\\azure-cli-extensions\\src\\azure-firewall']' returned non-zero exit status 1.
```

Thanks for supplying this wonderful tool.

Giacomo S. S.

PS: btw, is there a guide to put the source in debug?

**Comment by bquantump** [comment]
@gsscoder Can you give us some more information. What version of the CLI and azdev are you using?

 azdev --version
