### ISSUE TITLE
Error in `azdev setup` - `No such file or directory: '_NONE_/scripts/ci/cmdcov.yml'`

### ISSUE THREAD

**Issue by kevinhillinger** [Azure/azure-cli-dev-tools#407]
@bobjac and I are extension authors for an "external" extension that resides in its own repository, e.g. https://github.com/Azure/partnercenter-cli-extension

Since June 16, our CI is failing with the following error when calling `azdev setup`, regardless of args.
```
[Errno 2] No such file or directory: '_NONE_/scripts/ci/cmdcov.yml'
Traceback (most recent call last):
  File "/Users/kehilli/Workspace/github.com/partner-center-cli/env/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kehilli/Workspace/github.com/partner-center-cli/env/lib/python3.11/site-packages/knack/invocation.py", line 134, in execute
    self.commands_loader.load_arguments(command)
  File "/Users/kehilli/Workspace/github.com/partner-center-cli/env/lib/python3.11/site-packages/azdev/__main__.py", line 30, in load_arguments
    from azdev.params import load_arguments
  File "/Users/kehilli/Workspace/github.com/partner-center-cli/env/lib/python3.11/site-packages/azdev/params.py", line 13, in <module>
    from azdev.operations.linter import linter_severity_choices
  File "/Users/kehilli/Workspace/github.com/partner-center-cli/env/lib/python3.11/site-packages/azdev/operations/linter/__init__.py", line 21, in <module>
    from .linter import LinterManager, LinterScope, RuleError, LinterSeverity
  File "/Users/kehilli/Workspace/github.com/partner-center-cli/env/lib/python3.11/site-packages/azdev/operations/linter/linter.py", line 17, in <module>
    from azdev.operations.regex import (
  File "/Users/kehilli/Workspace/github.com/partner-center-cli/env/lib/python3.11/site-packages/azdev/operations/regex.py", line 19, in <module>
    with open(os.path.join(get_cli_repo_path(), 'scripts', 'ci', 'cmdcov.yml'), 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '_NONE_/scripts/ci/cmdcov.yml'
```

This happens locally as well after `pip install azdev`, which installs the latest version of azdev package.

We've tested back to version 0.1.48 and that version works.

**Comment by wangzelin007** [comment]
Hi @kevinhillinger,
Sorry for the inconvenience,  please upgrade to the latest azdev by `pip install azdev -U`.

**Comment by mboersma** [comment]
@wangzelin007 I'm seeing the same issue, and as far as i can tell I have the latest `azdev` installed:

```shell
% pip install azdev -U
Requirement already satisfied: azdev in ./env/lib/python3.10/site-packages (0.1.55)
```

You can see [here](https://github.com/Azure/azure-capi-cli-extension/actions/workflows/nightly.yml) this has been failing the nightly build on our CLI extension. Any workaround would be very helpful, thanks!

**Comment by laurawalker** [comment]
I also had this issue attempting to follow the instructions on https://github.com/Azure/azure-cli/blob/dev/doc/extensions/authoring.md to create a new extension without a local clone of the az cli repo. (Reverting to v0.1.48 firxt fixed this issue for me too).

**Comment by mboersma** [comment]
This doesn't seem to be a problem now (I tried v0.1.60), although I'm not sure where it was fixed (or if it's working for the original poster).
