### ISSUE TITLE
`azdev cli check-versions -m` does not work with short module names

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli-dev-tools#62]
```
(env) D:\GitRepos\github>azdev cli check-versions -m acs

==============================
| Verify CLI Module Versions |
==============================

MODULES: acs
'azure-cli-acs'
Traceback (most recent call last):
  File "d:\gitrepos\github\env\lib\site-packages\knack\cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "d:\gitrepos\github\env\lib\site-packages\knack\invocation.py", line 188, in execute
    cmd_result = parsed_args.func(params)
  File "d:\gitrepos\github\env\lib\site-packages\knack\commands.py", line 131, in __call__
    return self.handler(*args, **kwargs)
  File "d:\gitrepos\github\env\lib\site-packages\knack\commands.py", line 238, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "d:\gitrepos\github\azure-cli-dev-tools\azdev\operations\pypi.py", line 184, in verify_versions
    results.update(_compare_module_against_pypi(results, temp_dir, mod, mod_path))
  File "d:\gitrepos\github\azure-cli-dev-tools\azdev\operations\pypi.py", line 362, in _compare_module_against_pypi
    results[mod].update({
KeyError: 'azure-cli-acs'
```

It works if I specify `azure-cli-acs`

**Comment by tjprescott** [comment]
Additionally, this should support module(s) as a positional argument.
