### ISSUE TITLE
azdev test is not working

### ISSUE THREAD

**Issue by limingu** [Azure/azure-cli-dev-tools#65]
(env) C:\Users\limgu\workspace\azure-cli-extensions>azdev test storage-preview --discover --debug
Command arguments: ['test', 'storage-preview', '--discover', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x000001E17026B268>, <function OutputProducer.on_global_arguments at 0x000001E17034C510>, <function CLIQuery.on_global_arguments at 0x000001E1703750D0>]
Event: CommandInvoker.OnPreCommandTableCreate []
Event: CommandLoader.OnLoadCommandTable []
Event: CommandLoader.OnLoadArguments []
Event: CommandInvoker.OnPostCommandTableCreate []
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs []
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x000001E17034C598>, <function CLIQuery.handle_query_parameter at 0x000001E170375158>]

=============
| Run Tests |
=============

The tests are set to run against current profile latest.

=====================
| Discovering Tests |
=====================

Core Modules:

Command Modules:

Extensions: site-packages, storage-preview
No extension found at: C:\Users\limgu\workspace\azure-cli-extensions\env\Lib\site-packages\azext_*
local variable 'filepath' referenced before assignment
Traceback (most recent call last):
  File "c:\users\limgu\workspace\azure-cli-extensions\env\lib\site-packages\knack\cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "c:\users\limgu\workspace\azure-cli-extensions\env\lib\site-packages\knack\invocation.py", line 188, in execute
    cmd_result = parsed_args.func(params)
  File "c:\users\limgu\workspace\azure-cli-extensions\env\lib\site-packages\knack\commands.py", line 131, in __call__
    return self.handler(*args, **kwargs)
  File "c:\users\limgu\workspace\azure-cli-extensions\env\lib\site-packages\knack\commands.py", line 238, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "c:\users\limgu\workspace\azure-cli-extensions\env\lib\site-packages\azdev\operations\tests\__init__.py", line 43, in run_tests
    test_index = _get_test_index(profile, discover)
  File "c:\users\limgu\workspace\azure-cli-extensions\env\lib\site-packages\azdev\operations\tests\__init__.py", line 294, in _get_test_index
    test_index = _discover_tests(profile)
  File "c:\users\limgu\workspace\azure-cli-extensions\env\lib\site-packages\azdev\operations\tests\__init__.py", line 227, in _discover_tests
    import_name = os.path.basename(filepath)
UnboundLocalError: local variable 'filepath' referenced before assignment

My env folder is under workspace/azure-cli-extensions/ not under workspace.

**Comment by tjprescott** [comment]
Essentially, https://github.com/Azure/azure-cli-dev-tools/issues/45
