### ISSUE TITLE
azdev extension publish fails

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli-dev-tools#66]
```
azdev extension publish eventgrid --storage-account {account} --storage-container {container} --storage-subscription {sub} --update-index --debug

======================
| Publish Extensions |
======================


Building WHLs
===============

Building extension 'E:\Prev190201\CLI1000\azure-cli-extensions\src\eventgrid'...

Uploading WHLs
================

Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "e:\prev190201\cli1000\azure-cli-extensions\src\env\lib\site-packages\knack\cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "e:\prev190201\cli1000\azure-cli-extensions\src\env\lib\site-packages\knack\invocation.py", line 188, in execute
    cmd_result = parsed_args.func(params)
  File "e:\prev190201\cli1000\azure-cli-extensions\src\env\lib\site-packages\knack\commands.py", line 131, in __call__
    return self.handler(*args, **kwargs)
  File "e:\prev190201\cli1000\azure-cli-extensions\src\env\lib\site-packages\knack\commands.py", line 238, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "e:\prev190201\cli1000\azure-cli-extensions\src\env\lib\site-packages\azdev\operations\extensions\__init__.py", line 284, in publish_extensions
    exists = json.loads(cmd(command).result)['exists']
  File "C:\Users\ahamad.NTDEV\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\ahamad.NTDEV\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\ahamad.NTDEV\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

I believe the issue lies here:

**packages\azdev\operations\extensions\__init__.py", line 284, in publish_extensions
    exists = json.loads(cmd(command).result)['exists']**

There may be a permissions issue with running the exists command.

cc @ahamad-MS

**Comment by adewaleo** [comment]
+1, I had a similar problem with this command.

**Comment by tjprescott** [comment]
It seems like this occurs when you are not logged in to azure-cli. Try running `az login` and then retry.
