### ISSUE TITLE
az test not working with test result xml issue

### ISSUE THREAD

**Issue by ziwa-msft** [Azure/azure-cli-dev-tools#77]
Running: python -m pytest -p no:warnings --no-print-logs --junit-xml C:\Users\ziwa\.azdev\env_config\azure-cli\env3\test_results.xml f:\azure-cli\src\command
Traceback (most recent call last):
  File "C:\PYTHON27\Lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\PYTHON27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "F:\azure-cli\env3\lib\site-packages\pytest.py", line 67, in <module>
    raise SystemExit(pytest.main())
  File "F:\azure-cli\env3\lib\site-packages\_pytest\config\__init__.py", line 55, in main
    config = _prepareconfig(args, plugins)
  File "F:\azure-cli\env3\lib\site-packages\_pytest\config\__init__.py", line 180, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "F:\azure-cli\env3\lib\site-packages\pluggy\hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "F:\azure-cli\env3\lib\site-packages\pluggy\manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "F:\azure-cli\env3\lib\site-packages\pluggy\manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "F:\azure-cli\env3\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "F:\azure-cli\env3\lib\site-packages\_pytest\helpconfig.py", line 89, in pytest_cmdline_parse
    config = outcome.get_result()
  File "F:\azure-cli\env3\lib\site-packages\pluggy\callers.py", line 81, in get_result
    _reraise(*ex)  # noqa
  File "F:\azure-cli\env3\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "F:\azure-cli\env3\lib\site-packages\_pytest\config\__init__.py", line 612, in pytest_cmdline_parse
    self.parse(args)
  File "F:\azure-cli\env3\lib\site-packages\_pytest\config\__init__.py", line 777, in parse
    self._preparse(args, addopts=addopts)
  File "F:\azure-cli\env3\lib\site-packages\_pytest\config\__init__.py", line 729, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "F:\azure-cli\env3\lib\site-packages\pluggy\manager.py", line 280, in load_setuptools_entrypoints
    message="Plugin %r could not be loaded: %s!" % (ep.name, e),
pluggy.manager.PluginValidationError: Plugin 'xdist.looponfail' could not be loaded: (pytest 3.6.4 (f:\azure-cli\env3\lib\site-packages), Requirement.parse('

 Results
=========

[Errno 2] No such file or directory: 'C:\\Users\\ziwa\\.azdev\\env_config\\azure-cli\\env3\\test_results.xml'
Traceback (most recent call last):
  File "f:\azure-cli\env3\lib\site-packages\knack\cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "f:\azure-cli\env3\lib\site-packages\knack\invocation.py", line 188, in execute
    cmd_result = parsed_args.func(params)
  File "f:\azure-cli\env3\lib\site-packages\knack\commands.py", line 131, in __call__
    return self.handler(*args, **kwargs)
  File "f:\azure-cli\env3\lib\site-packages\knack\commands.py", line 238, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "f:\azure-cli\env3\lib\site-packages\azdev\operations\tests\__init__.py", line 91, in run_tests
    _summarize_test_results(xml_path)
  File "f:\azure-cli\env3\lib\site-packages\azdev\operations\tests\__init__.py", line 316, in _summarize_test_results
    root = ElementTree.parse(xml_path).getroot()
  File "C:\PYTHON27\Lib\xml\etree\ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "C:\PYTHON27\Lib\xml\etree\ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: 'C:\\Users\\ziwa\\.azdev\\env_config\\azure-cli\\env3\\test_results.xml'

my azure-cli root is F:\azure-cli

**Comment by ziwa-msft** [comment]
fixed with pip install --upgrade pytest

**Comment by ziwa-msft** [comment]
should this be done by the azdev setup process? looks like the old version of pytest is not compatible and not being upgraded correctly.

**Comment by tjprescott** [comment]
Do you know which version of pytest you had prior to updating?

**Comment by ziwa-msft** [comment]
it is 3.6.4
