### ISSUE TITLE
azdev test started failing with pytest error

### ISSUE THREAD

**Issue by ziwa-msft** [Azure/azure-cli-dev-tools#82]
azure-cli-nspkg' not found. If newly added, re-run with --discover
ERROR: usage: pytest.py [options] [file_or_dir] [file_or_dir] [...]
pytest.py: error: unrecognized arguments: -n auto
  inifile: None
  rootdir: E:\Github2\azure-cli

 Results
=========

[Errno 2] No such file or directory: 'C:\\Users\\ziwa\\.azdev\\env_config\\Github2\\azure-cli\\env\\test_results.xml'
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\knack\cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "c:\python27\lib\site-packages\knack\invocation.py", line 188, in execute
    cmd_result = parsed_args.func(params)
  File "c:\python27\lib\site-packages\knack\commands.py", line 131, in __call__
    return self.handler(*args, **kwargs)
  File "c:\python27\lib\site-packages\knack\commands.py", line 238, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "c:\python27\lib\site-packages\azdev\operations\tests\__init__.py", line 91, in run_tests
    _summarize_test_results(xml_path)
  File "c:\python27\lib\site-packages\azdev\operations\tests\__init__.py", line 315, in _summarize_test_results
    root = ElementTree.parse(xml_path).getroot()
  File "c:\python27\lib\xml\etree\ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "c:\python27\lib\xml\etree\ElementTree.py", line 647, in parse
    source = open(source, "rb")
IOError: [Errno 2] No such file or directory: 'C:\\Users\\ziwa\\.azdev\\env_config\\Github2\\azure-cli\\env\\test_results.xml'

**Comment by ziwa-msft** [comment]
Everything was working before I synced to the latest.

**Comment by tjprescott** [comment]
This is fixed by running `pip install --upgrade pytest`. The next release of azdev will fix this.

**Comment by ziwa-msft** [comment]
Still having issue after upgrade:

Requirement already up-to-date: pytest in e:\github2\azure-cli\env\lib\site-packages (4.5.0)

**Comment by tjprescott** [comment]
`pip install --upgrade pytest -I`

If that doesn't work please run `pip list` and paste the output.
